# Project Work

Durante il workshop lavoreremo su un progetto che vuole realizzare un innovativo Motore di Ricerca per i Pokémon.

Tale motore di ricerca includerà una speciale e super segreta tecnologia in grado di identificare i k Pokémon più simili ad una data query di ricerca.

Progetteremo e svilupperemo passo passo questa speciale tecnologia che avrà l'obiettivo di calcolare un punteggio di similirità tra Pokémon, sia esitenti che immaginari, identificati da un insieme di specifiche caratteristiche.

🧑‍💻 Happy coding! 👩‍💻



### Sottoproblema 1: Prendere in input dei dati dall'utente e memorizzarli sottoforma di numeri

Concetti teorici correlati:
- variabili
- funzione input
- funzione print 
- tipi di dato
- operazioni con i dati

In [13]:
# Qui andremo a prendere 6 input dall'utente e a trasformarli in variabili float

import numpy as np

hp = int(input("Inserisci un valore per HP"))
attack = int(input("Inserisci un valore per attack"))
defense = int(input("Inserisci un valore per defense"))
sp_atk = int(input("Inserisci un valore per attacco speciale"))
sp_def = int(input("Inserisci un valore per difesa speciale"))
speed = int(input("Inserisci un valore per speed"))




Inserisci un valore per HP 40
Inserisci un valore per attack 50
Inserisci un valore per defense 60
Inserisci un valore per attacco speciale 70
Inserisci un valore per difesa speciale 80
Inserisci un valore per speed 90


In [15]:
user_input = np.array([hp, attack, defense, sp_atk, sp_def, speed])
user_input

array([40, 50, 60, 70, 80, 90])

### Sottoproblema 2.a Leggere dal dataset tutti i dati relativi ai Pokemon

Concetti teorici correlati:
- liste e accesso ai loro elementi
- cicli for per scorrere le liste
- matrici
- file CSV e loro lettura
- apertura e lettura di un file in Python
- dataset
- f-strings

Se sei è su Colab
```python
import os
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/beginners')
```

In [19]:
# Qui andremo ad aprire il dataset dei pokemon e ad assegnarlo ad una variabile

import csv

dataset = []

with open("dataset/pokemon.csv", "r") as file:
    reader = csv.DictReader(file)
    for row in reader:
        dataset.append(row)

print(type(dataset[0]["HP"]))

<class 'str'>


### Sottoproblema 2.b Utilizzare una funzione per stabilire un grado di similarità

Concetti teorici correlati:
- espressioni matematiche più complesse e precedenza degli operatori
- modulo math
- funzioni
  - input/output di una funzione
  - argomenti

In [22]:
# Qui andremo a creare e testare le funzioni per
# - calcolo della distanza euclidea
# - normalizzazione
# Inoltre ci andremo a prendere le colonne con i soli valori numerici dal dataset

bulbasaur = dataset[0]
print(bulbasaur)
print(user_input)


# 1 - creare un array di numpy che contiene i soli valori numerici -> 
# 2 - implementare euclidean_distance
# 3 - prendo tutti i valori su un singolo asse -> vettore colonna per HP 
# 4 - implementazione minmax_normalize
def euclidean_distance(a, b):
    pass

def minmax_normalize(axis):
    pass

{'#': '1', 'Name': 'Bulbasaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '318', 'HP': '45', 'Attack': '49', 'Defense': '49', 'Sp. Atk': '65', 'Sp. Def': '65', 'Speed': '45', 'Generation': '1', 'Legendary': 'False'}
[40 50 60 70 80 90]


In [73]:
np_dataset = np.array([ list(r.values()) for r in dataset ])
user_input = user_input.reshape((1, -1))

print(user_input.shape)

numeric_columns = np_dataset[:, 5:11].astype(int)

def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

def minmax_normalize(dataset):
    min_value = np.min(dataset, axis=0)
    max_value = np.max(dataset, axis=0)
    return (dataset - min_value)/(max_value - min_value)

norm_dataset= minmax_normalize(numeric_columns)

print(numeric_columns[0])
print(norm_dataset[0])

# partiamo dall'unione dei valori numerici e dell'input utente
# euclidean_distance per ogni user_input/pokemon dataset
# [ [index_bulbasaur, distance_bulbasaur ], [..., ...] ] -> ndarray
# sort dell'nd array -> 



(1, 6)
[45 49 49 65 65 45]
[0.17322835 0.23783784 0.19555556 0.29891304 0.21428571 0.22857143]


### Sottoproblema 2.c Trovare i k pokemon più simili utilizzando la funzione di similarità

Concetti teorici correlati:
- cicli for
- strutture dati complesse (liste di tuple?)
- sort 
- funzioni lambda
- array slicing

In [33]:
# Qui andremo ad unire i pezzi:
# - Partiamo dall'input dell'utente e creiamo una lista corrispondente ad un pokemon "fittizio"
# - Aggiungiamo al dataset e normalizziamo (ottenendo un dataset normalizzato)
# - Estraiamo ultima riga (corrispondente al pokemon fittizio)
# - in un ciclo for calcoliamo le distanze e le inseriamo nella struttura dati complessa
# - orinamento tramite sort e lambda
# - estraiamo i primi K elementi

### Sottoproblema 3 Visualizzare i risultati

Concetti teorici correlati:
- f-strings
- funzioni

In [34]:
# Qui andremo a creare una funzione che partendo dai K indici ci costruisce K stringhe tramite funzione ed f-strings

### Bonus track Visualizzare i Pokemon

Concetti di teoria correlati:
- `list comprehension`

Se sei sul tuo Jupyter notebook usa il seguente snippet di codice: 

```python
from IPython.display import Image

for n,p in enumerate(best_pokemon):
    print('-'*50)
    print(n+1)
    print(pokemon_dataset[p[0]][1])
    display(Image(f"resized/{pokemon_dataset[p[0]][0]}.jpg")),
    print('-'*50)
```

In [74]:
class KNNSearchEngine:
    def __init__(self, data_path, features, distance_function='euclidean'):
        self.df = pd.read_csv(data_path)
        self.features = features
        self.X = self.df[features].values
        self.X_scaled = self.standardize(self.X)
        self.distance_function = self.get_distance_function(distance_function)
        self.inv_cov_matrix = np.linalg.inv(np.cov(self.X_scaled.T))
        
    def standardize(self, data):
        mean = data.mean(axis=0)
        std = data.std(axis=0)
        return (data - mean) / std

    def euclidean_distance(self, a, b):
        return np.sqrt(np.sum((a - b) ** 2, axis=1))
    
    def manhattan_distance(self, a, b):
        return np.sum(np.abs(a - b), axis=1)
    
    def mahalanobis_distance(self, a, b):
        delta = a - b
        return np.sqrt(np.sum(delta @ self.inv_cov_matrix * delta, axis=1))

    def get_distance_function(self, name):
        if name == 'euclidean':
            return self.euclidean_distance
        elif name == 'manhattan':
            return self.manhattan_distance
        elif name == 'mahalanobis':
            return self.mahalanobis_distance
        else:
            raise ValueError(f"Unsupported distance function: {name}")

    def knn_search(self, query, k=5):
        distances = self.distance_function(self.X_scaled, query)
        nearest_indices = distances.argsort()[:k]
        return nearest_indices

    def find_similar_pokemon(self, pokemon_name, n_neighbors=5):
        if pokemon_name not in self.df['Name'].values:
            raise ValueError(f"{pokemon_name} not found in the dataset.")
        
        pokemon_index = self.df[self.df['Name'] == pokemon_name].index[0]
        query = self.X_scaled[pokemon_index].reshape(1, -1)
        neighbors_indices = self.knn_search(query, k=n_neighbors)
        return self.df.iloc[neighbors_indices]

    def __repr__(self):
        return f"KNNSearchEngine(data_path={self.df}, features={self.features}, distance_function={self.distance_function.__name__})"
    
    def __getitem__(self, index):
        return self.df.iloc[index]
    
    def __len__(self):
        return len(self.df)
    
    def __call__(self, pokemon_name, n_neighbors=5):
        return self.find_similar_pokemon(pokemon_name, n_neighbors)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [2]:
import numpy as np
import pandas as pd

from .models import Pokemon

class KNNSearchEngine:
    def __init__(self, data_path, features=["HP", "Attack", "Defense" ], distance_function='euclidean'):
        self.df = pd.read_csv(data_path)
        self.features = features
        self.X = self.df[features].values
        self.X_scaled = self.standardize(self.X)
        self.distance_function = self.get_distance_function(distance_function)
        self.inv_cov_matrix = np.linalg.inv(np.cov(self.X_scaled.T))
        
    def standardize(self, data):
        mean = data.mean(axis=0)
        std = data.std(axis=0)
        return (data - mean) / std

    def euclidean_distance(self, a, b):
        return np.sqrt(np.sum((a - b) ** 2, axis=1))
    
    def manhattan_distance(self, a, b):
        return np.sum(np.abs(a - b), axis=1)
    
    def mahalanobis_distance(self, a, b):
        delta = a - b
        return np.sqrt(np.sum(delta @ self.inv_cov_matrix * delta, axis=1))

    def get_distance_function(self, name):
        if name == 'euclidean':
            return self.euclidean_distance
        elif name == 'manhattan':
            return self.manhattan_distance
        elif name == 'mahalanobis':
            return self.mahalanobis_distance
        else:
            raise ValueError(f"Unsupported distance function: {name}")

    def knn_search(self, query, k=5):
        distances = self.distance_function(self.X_scaled, query)
        nearest_indices = distances.argsort()[:k]
        return nearest_indices

    def find_similar_pokemon(self, pokemon_name, n_neighbors=5):
        if pokemon_name not in self.df['Name'].values:
            raise ValueError(f"{pokemon_name} not found in the dataset.")
        
        pokemon_index = self.df[self.df['Name'] == pokemon_name].index[0]
        query = self.X_scaled[pokemon_index].reshape(1, -1)
        neighbors_indices = self.knn_search(query, k=n_neighbors)
        return self.df.iloc[neighbors_indices]

    def __repr__(self):
        return f"KNNSearchEngine(data_path={self.df}, features={self.features}, distance_function={self.distance_function.__name__})"
    
    def __getitem__(self, index):
        return self.df.iloc[index]
    
    def __len__(self):
        return len(self.df)
    
    def __call__(self, pokemon_name, n_neighbors=5):
        return self.find_similar_pokemon(pokemon_name, n_neighbors)
    

# Esempio di utilizzo
if __name__ == "__main__":
    data_path = '../dataset/pokemon.csv'
    features = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']
    
    # Crea il motore di ricerca utilizzando la distanza euclidea
    search_engine = KNNSearchEngine(data_path, features, distance_function='euclidean')
    similar_pokemon = search_engine.find_similar_pokemon('Pikachu', n_neighbors=5)
    print("Similar Pokémon using Euclidean distance:")
    print(similar_pokemon)
    
    # Crea il motore di ricerca utilizzando la distanza di Manhattan
    search_engine_manhattan = KNNSearchEngine(data_path, features, distance_function='manhattan')
    similar_pokemon_manhattan = search_engine_manhattan.find_similar_pokemon('Pikachu', n_neighbors=5)
    print("\nSimilar Pokémon using Manhattan distance:")
    print(similar_pokemon_manhattan)
    
    # Crea il motore di ricerca utilizzando la distanza di Mahalanobis
    search_engine_mahalanobis = KNNSearchEngine(data_path, features, distance_function='mahalanobis')
    similar_pokemon_mahalanobis = search_engine_mahalanobis.find_similar_pokemon('Pikachu', n_neighbors=5)
    print("\nSimilar Pokémon using Mahalanobis distance:")
    print(similar_pokemon_mahalanobis)
    
    # Esempio di utilizzo dei metodi dunder
    print("\nRepresentation of search engine:")
    print(search_engine)
    
    print("\nLength of dataset:")
    print(len(search_engine))
    
    print("\nFirst Pokémon in the dataset:")
    print(search_engine[0])
    
    print("\nUsing the search engine as a callable:")
    print(search_engine('Pikachu', n_neighbors=5))


ImportError: attempted relative import with no known parent package

In [7]:
class CallableObject:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def test_method(self):
        print("test_method")
    
    def __call__(self):
        print("call")
        self.test_method()

obj = CallableObject(2, 3)
print(obj)

obj()


call
test_method


In [9]:
a = np.array([40, 50, 20, 10, 5, 17, 21])

In [13]:
a[np.argsort(a)[:5]]

array([ 5, 10, 17, 20, 21])

In [14]:
df

NameError: name 'df' is not defined

In [15]:
import pandas as pd


In [17]:
df = pd.read_csv("dataset/pokemon.csv")

In [21]:
df[(df['Legendary'] == False) & (df['Total'] > 400)]

#                   Name  Type 1  Type 2  Total  HP  Attack  Defense  \
1      2                Ivysaur   Grass  Poison    405  60      62       63   
2      3               Venusaur   Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur   Grass  Poison    625  80     100      123   
5      5             Charmeleon    Fire     NaN    405  58      64       58   
6      6              Charizard    Fire  Flying    534  78      84       78   
..   ...                    ...     ...     ...    ...  ..     ...      ...   
785  711    GourgeistSmall Size   Ghost   Grass    494  55      85      122   
786  711    GourgeistLarge Size   Ghost   Grass    494  75      95      122   
787  711    GourgeistSuper Size   Ghost   Grass    494  85     100      122   
789  713                Avalugg     Ice     NaN    514  95     117      184   
791  715                Noivern  Flying  Dragon    535  85      70       80   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
5         80       65     80           1      False  
6        109       85    100           1      False  
..       ...      ...    ...         ...        ...  
785       58       75     99           6      False  
786       58       75     69           6      False  
787       58       75     54           6      False  
789       44       46     28           6      False  
791       97       80    123           6      False  

[428 rows x 13 columns]